name: LGTM
on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]

jobs:
  lgtm:
    runs-on: ubuntu-latest
    steps:
      - name: LGTM
        uses: Doarakko/action-lgtmoon@v1.0
        if: >-
          contains(github.event.comment.body, 'lgtm')
          || contains(github.event.review.body, 'lgtm')
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}

  auto_approve:
    needs: lgtm
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve PR on LGTM
        uses: actions/checkout@v3
      - name: Approve PR using gh CLI
        env:
          GH_TOKEN: ${{ secrets.BOT_PAT }}
        run: |
          gh pr review ${{ github.event.pull_request.html_url }} --approve
