name: Auto-approve on LGTM

on:
  issue_comment:
    types: [created]

jobs:
  auto_approve:
    if: github.event.comment.body == 'LGTM'
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
