name: Auto-approve on LGTM

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

jobs:
  auto_approve:
    if: contains(github.event.comment.body, 'LGTM') && github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.issue.number }}
